apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: container-openshift-ifie
      build: container-openshift-ifie
    name: container-openshift-ifie-original
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: chrira/container-openshift-ifie
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: container-openshift-ifie
      build: container-openshift-ifie
    name: container-openshift-ifie
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: container-openshift-ifie:latest
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 10Mi
    source:
      dockerfile: |-
        FROM chrira/container-openshift-ifie:latest
        USER golang
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: container-openshift-ifie-original:latest
      type: Docker
    triggers: []
  status:
    lastVersion: 0
