apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: deploymentconfig-s2i-template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: spring-boot-s2i
    name: spring-boot-s2i
  spec:
    replicas: 1
    selector:
      deploymentconfig: spring-boot-s2i
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          deploymentconfig: spring-boot-s2i
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/${PROJECT_NAME}/spring-boot-s2i:latest
          name: spring-boot-s2i
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot-s2i
        from:
          kind: ImageStreamTag
          name: spring-boot-s2i:latest
      type: ImageChange
parameters:
- description: OpenShift Project Name
  name: PROJECT_NAME